#cloud-config
# hostname: tks
# manage_etc_hosts: false
# manage_resolv_conf: true
# chpasswd:
  # expire: False
users:
  - name: tks
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - sudo
    lock_passwd: true
    ssh-authorized-keys:
      - "{{ TEMPLATE_SSH_KEY }}"
write_files:
  - path: /etc/resolvconf/resolv.conf.d/base
    content: |
        nameserver {{ TEMPLATE_NAMESERVER }}
        search {{ TEMPLATE_SEARCHDOMAIN }}
runcmd:
  - [ systemctl, restart, resolvconf ]
