#cloud-config
users:
  - name: tks
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - sudo
    lock_passwd: true
    ssh-authorized-keys:
      - "{{ TEMPLATE_SSH_PUBLIC_KEY }}"
write_files:
  - path: /etc/resolvconf/resolv.conf.d/base
    content: |
        nameserver {{ TEMPLATE_NAMESERVER }}
        search {{ TEMPLATE_SEARCH_DOMAIN }}
runcmd:
  - [ systemctl, restart, resolvconf ]
