- hosts: proxmox
  gather_facts: False
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/variables.yml"

    - name: Creating a Resource Pool
      command: >
        pvesh create /pools
        -poolid "{{ TKS_POOL_NAME }}"
        --Comment "Resources pertaining to TKS"
      when:
        - TKS_CREATE_POOL == 'true'
      ignore_errors: true


