- hosts: proxmox
  gather_facts: False
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/variables.yml"

    - import_role:
        name: Create_Template


- hosts: k8s_template
  gather_facts: false
  become: true
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/variables.yml"

    - wait_for_connection:

    - import_role:
        name: Configure_Template


- hosts: proxmox
  gather_facts: False
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/variables.yml"

    - name: Powering off the VM
      command: qm stop {{ TEMPLATE_VM_ID }}

    - name: Converting the VM into a template
      command: qm template {{ TEMPLATE_VM_ID }}
