apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
metadata:
  name: kubelet-config
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
metadata:
  name: init-config
bootstrapTokens:
  - token: "{{ TEMPLATE_K8S_JOIN_TOKEN }}"
    ttl: "0"
certificateKey: "{{ TEMPLATE_K8S_CERT_KEY }}"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: cluster-config
apiServer:
  extraArgs:
    cloud-provider: external
clusterName: "{{ TEMPLATE_K8S_CLUSTER_NAME }}"
kubernetesVersion: "{{ TEMPLATE_K8S_VERSION }}"
networking:
  podSubnet: "{{ TEMPLATE_K8S_POD_NETWORK_CIDR }}"
  serviceSubnet: "{{ TEMPLATE_K8S_SVC_NETWORK_CIDR }}"
skip-certificate-key-print: true
skip-token-print: true
controlPlaneEndpoint: "{{ TEMPLATE_K8S_LB_HN }}.{{ TEMPLATE_K8S_SEARCHDOMAIN }}:6443"
