apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "{{ TEMPLATE_K8S_JOIN_TOKEN }}"
    unsafeSkipCAVerification: true
    apiServerEndpoint: "{{ TEMPLATE_K8S_LB_HN }}.{{ TEMPLATE_K8S_SEARCH_DOMAIN }}:6443"
